# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A BLOG
name: XPIGM
email: xpigm@outlook.com
#location: Beijing
#company: MyCompany
#company_url: my_company_website
description: java
aword: The unexamined life is not worth living.
favicon: favicon.png # Image must be in assets/images


repository: xpigm/xpigm.github.io
github_url: https://github.com/xpigm

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://xpigm.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk

# https://disqus.com
disqus:
  username: xpigm
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true  
    
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: xpigm
  repo: xpigm.github.io
  oauth:
    client_id: 5df79a27aac31c441a6f
    client_secret: 0274d85cd24ea36edaddbc5bd283b2b5b5629ac0
        
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: xpigm
  repo: xpigm.github.io
  clientID: 5df79a27aac31c441a6f
  clientSecret: 0274d85cd24ea36edaddbc5bd283b2b5b5629ac0
    

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

#  -
#    href: /open-source
#    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
#analytics :
#  provider : google
#  google :
#      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

